using RemoteHubStudio.UI.Controls;

namespace RemoteHubStudio.UI.Dialogs;

partial class SettingsForm
{
    /// <summary>
    /// Creates the complete designer-serializable settings visual tree. / 创建可由设计器完整序列化的设置可视树。
    /// </summary>
    private void InitializeComponent()
    {
        _languageLabel = new AntdUI.Label();
        _languageSelect = new AntdUI.Select();
        _themeLabel = new AntdUI.Label();
        _themeSelect = new AntdUI.Select();
        _encryptionLabel = new AntdUI.Label();
        _encryptionSwitch = new AntdUI.Switch();
        _unsafePasswordLabel = new AntdUI.Label();
        _unsafePasswordSwitch = new AntdUI.Switch();
        _includeSecretsLabel = new AntdUI.Label();
        _includeSecretsSwitch = new AntdUI.Switch();
        _trayLabel = new AntdUI.Label();
        _traySwitch = new AntdUI.Switch();
        _confirmDeleteLabel = new AntdUI.Label();
        _confirmDeleteSwitch = new AntdUI.Switch();
        _sidebarLabel = new AntdUI.Label();
        _sidebarSwitch = new AntdUI.Switch();
        _expiryDaysLabel = new AntdUI.Label();
        _expiryDaysInput = new AntdUI.InputNumber();
        _pingTimeoutLabel = new AntdUI.Label();
        _pingTimeoutInput = new AntdUI.InputNumber();
        _concurrencyLabel = new AntdUI.Label();
        _concurrencyInput = new AntdUI.InputNumber();
        _encryptionWarning = new AntdUI.Label();
        _commandLineWarning = new AntdUI.Label();
        _exportWarning = new AntdUI.Label();
        _puttyPathLabel = new AntdUI.Label();
        _puttyPathInput = new AntdUI.Input();
        _xshellPathLabel = new AntdUI.Label();
        _xshellPathInput = new AntdUI.Input();
        _xftpPathLabel = new AntdUI.Label();
        _xftpPathInput = new AntdUI.Input();
        _winscpPathLabel = new AntdUI.Label();
        _winscpPathInput = new AntdUI.Input();
        _secureCrtPathLabel = new AntdUI.Label();
        _secureCrtPathInput = new AntdUI.Input();
        _mobaXtermPathLabel = new AntdUI.Label();
        _mobaXtermPathInput = new AntdUI.Input();
        _tightVncPathLabel = new AntdUI.Label();
        _tightVncPathInput = new AntdUI.Input();
        _realVncPathLabel = new AntdUI.Label();
        _realVncPathInput = new AntdUI.Input();
        _ultraVncPathLabel = new AntdUI.Label();
        _ultraVncPathInput = new AntdUI.Input();
        _radminPathLabel = new AntdUI.Label();
        _radminPathInput = new AntdUI.Input();
        _toDeskPathLabel = new AntdUI.Label();
        _toDeskPathInput = new AntdUI.Input();
        _rustDeskPathLabel = new AntdUI.Label();
        _rustDeskPathInput = new AntdUI.Input();
        _openDataFolderLabel = new AntdUI.Label();
        _openDataFolderButton = new AntdUI.Button();
        _aboutLabel = new AntdUI.Label();
        _aboutButton = new AntdUI.Button();
        _saveButton = new AntdUI.Button();
        _cancelButton = new AntdUI.Button();
        _appearanceGrid = new ResponsiveFieldGrid();
        _securityGrid = new ResponsiveFieldGrid();
        _behaviorGrid = new ResponsiveFieldGrid();
        _toolPathGrid = new ResponsiveFieldGrid();
        _appearanceSection = new AntdUI.Panel();
        _securitySection = new AntdUI.Panel();
        _encryptionNoticeSection = new AntdUI.Panel();
        _commandLineNoticeSection = new AntdUI.Panel();
        _exportNoticeSection = new AntdUI.Panel();
        _behaviorSection = new AntdUI.Panel();
        _clientsSection = new AntdUI.Panel();
        _appearanceTitle = new AntdUI.Label();
        _securityTitle = new AntdUI.Label();
        _encryptionNoticeTitle = new AntdUI.Label();
        _commandLineNoticeTitle = new AntdUI.Label();
        _exportNoticeTitle = new AntdUI.Label();
        _behaviorTitle = new AntdUI.Label();
        _clientsTitle = new AntdUI.Label();
        _appearanceGrid.SuspendLayout();
        _securityGrid.SuspendLayout();
        _behaviorGrid.SuspendLayout();
        _toolPathGrid.SuspendLayout();
        _appearanceSection.SuspendLayout();
        _securitySection.SuspendLayout();
        _encryptionNoticeSection.SuspendLayout();
        _commandLineNoticeSection.SuspendLayout();
        _exportNoticeSection.SuspendLayout();
        _behaviorSection.SuspendLayout();
        _clientsSection.SuspendLayout();
        _contentFlow.SuspendLayout();
        _footerFlow.SuspendLayout();
        SuspendLayout();

        _languageLabel.Dock = DockStyle.Fill;
        _languageLabel.Margin = new Padding(8, 5, 4, 5);
        _languageLabel.Name = "languageLabel";
        _languageLabel.Text = "语言 / Language";
        _languageLabel.TextAlign = ContentAlignment.MiddleLeft;

        _languageSelect.PlaceholderText = "跟随系统语言 / Follow system language";
        _languageSelect.DropDownArrow = true;
        _languageSelect.ListAutoWidth = true;
        _languageSelect.Radius = 8;
        _languageSelect.Name = "languageSelect";
        _languageSelect.WheelModifyEnabled = false;

        _themeLabel.Dock = DockStyle.Fill;
        _themeLabel.Margin = new Padding(8, 5, 4, 5);
        _themeLabel.Name = "_themeLabel";
        _themeLabel.Text = "主题 / Theme";
        _themeLabel.TextAlign = ContentAlignment.MiddleLeft;

        _themeSelect.PlaceholderText = "跟随系统 / Follow system";
        _themeSelect.DropDownArrow = true;
        _themeSelect.ListAutoWidth = true;
        _themeSelect.Radius = 8;
        _themeSelect.Name = "themeSelect";
        _themeSelect.WheelModifyEnabled = false;
        _encryptionLabel.Dock = DockStyle.Fill;
        _encryptionLabel.Margin = new Padding(8, 5, 4, 5);
        _encryptionLabel.Name = "_encryptionLabel";
        _encryptionLabel.Text = "本地数据加密 / Local encryption";
        _encryptionLabel.TextAlign = ContentAlignment.MiddleLeft;

        _encryptionSwitch.AutoCheck = true;
        _encryptionSwitch.AccessibleDescription = "启用本地数据加密 / Encrypt local data";
        _encryptionSwitch.Name = "encryptionSwitch";

        _unsafePasswordLabel.Dock = DockStyle.Fill;
        _unsafePasswordLabel.Margin = new Padding(8, 5, 4, 5);
        _unsafePasswordLabel.Name = "_unsafePasswordLabel";
        _unsafePasswordLabel.Text = "密码自动传递 / Password passing";
        _unsafePasswordLabel.TextAlign = ContentAlignment.MiddleLeft;

        _unsafePasswordSwitch.AutoCheck = true;
        _unsafePasswordSwitch.AccessibleDescription = "允许自动传递密码 / Allow automatic password passing";
        _unsafePasswordSwitch.Checked = true;
        _unsafePasswordSwitch.Name = "unsafePasswordSwitch";

        _includeSecretsLabel.Dock = DockStyle.Fill;
        _includeSecretsLabel.Margin = new Padding(8, 5, 4, 5);
        _includeSecretsLabel.Name = "_includeSecretsLabel";
        _includeSecretsLabel.Text = "导出保存密码 / Export saved passwords";
        _includeSecretsLabel.TextAlign = ContentAlignment.MiddleLeft;

        _includeSecretsSwitch.AutoCheck = true;
        _includeSecretsSwitch.AccessibleDescription = "导出默认包含已保存密码 / Include saved passwords in exports";
        _includeSecretsSwitch.Name = "includeSecretsSwitch";

        _trayLabel.Dock = DockStyle.Fill;
        _trayLabel.Margin = new Padding(8, 5, 4, 5);
        _trayLabel.Name = "_trayLabel";
        _trayLabel.Text = "关闭窗口时收起到托盘 / Close to tray";
        _trayLabel.TextAlign = ContentAlignment.MiddleLeft;

        _traySwitch.AutoCheck = true;
        _traySwitch.AccessibleDescription = "关闭时最小化到托盘 / Minimize to tray on close";
        _traySwitch.Name = "traySwitch";

        _confirmDeleteLabel.Dock = DockStyle.Fill;
        _confirmDeleteLabel.Margin = new Padding(8, 5, 4, 5);
        _confirmDeleteLabel.Name = "_confirmDeleteLabel";
        _confirmDeleteLabel.Text = "删除前确认 / Confirm deletion";
        _confirmDeleteLabel.TextAlign = ContentAlignment.MiddleLeft;

        _confirmDeleteSwitch.AutoCheck = true;
        _confirmDeleteSwitch.AccessibleDescription = "删除前确认 / Confirm before delete";
        _confirmDeleteSwitch.Checked = true;
        _confirmDeleteSwitch.Name = "confirmDeleteSwitch";

        _sidebarLabel.Dock = DockStyle.Fill;
        _sidebarLabel.Margin = new Padding(8, 5, 4, 5);
        _sidebarLabel.Name = "_sidebarLabel";
        _sidebarLabel.Text = "启动折叠 / Start collapsed";
        _sidebarLabel.TextAlign = ContentAlignment.MiddleLeft;

        _sidebarSwitch.AutoCheck = true;
        _sidebarSwitch.AccessibleDescription = "启动时折叠侧边栏 / Start with sidebar collapsed";
        _sidebarSwitch.Name = "sidebarSwitch";

        _expiryDaysLabel.Dock = DockStyle.Fill;
        _expiryDaysLabel.Margin = new Padding(8, 5, 4, 5);
        _expiryDaysLabel.Name = "_expiryDaysLabel";
        _expiryDaysLabel.Text = "到期预警天数 / Expiry days";
        _expiryDaysLabel.TextAlign = ContentAlignment.MiddleLeft;

        _expiryDaysInput.Minimum = 0;
        _expiryDaysInput.Maximum = 3650;
        _expiryDaysInput.Value = 30;
        _expiryDaysInput.DecimalPlaces = 0;
        _expiryDaysInput.ShowControl = true;
        _expiryDaysInput.Radius = 8;
        _expiryDaysInput.Name = "expiryDaysInput";
        _expiryDaysInput.WheelModifyEnabled = false;

        _pingTimeoutLabel.Dock = DockStyle.Fill;
        _pingTimeoutLabel.Margin = new Padding(8, 5, 4, 5);
        _pingTimeoutLabel.Name = "_pingTimeoutLabel";
        _pingTimeoutLabel.Text = "Ping 超时（毫秒）/ Ping timeout";
        _pingTimeoutLabel.TextAlign = ContentAlignment.MiddleLeft;

        _pingTimeoutInput.Minimum = 100;
        _pingTimeoutInput.Maximum = 60000;
        _pingTimeoutInput.Value = 1500;
        _pingTimeoutInput.DecimalPlaces = 0;
        _pingTimeoutInput.ShowControl = true;
        _pingTimeoutInput.Radius = 8;
        _pingTimeoutInput.Name = "pingTimeoutInput";
        _pingTimeoutInput.WheelModifyEnabled = false;

        _concurrencyLabel.Dock = DockStyle.Fill;
        _concurrencyLabel.Margin = new Padding(8, 5, 4, 5);
        _concurrencyLabel.Name = "_concurrencyLabel";
        _concurrencyLabel.Text = "状态检测并发 / Check concurrency";
        _concurrencyLabel.TextAlign = ContentAlignment.MiddleLeft;

        _concurrencyInput.Minimum = 1;
        _concurrencyInput.Maximum = 128;
        _concurrencyInput.Value = 8;
        _concurrencyInput.DecimalPlaces = 0;
        _concurrencyInput.ShowControl = true;
        _concurrencyInput.Radius = 8;
        _concurrencyInput.Name = "concurrencyInput";
        _concurrencyInput.WheelModifyEnabled = false;

        _encryptionWarning.Dock = DockStyle.Top;
        _encryptionWarning.Height = 96;
        _encryptionWarning.TextMultiLine = true;
        _encryptionWarning.TextAlign = ContentAlignment.MiddleLeft;
        _encryptionWarning.Padding = new Padding(12, 8, 12, 8);
        _encryptionWarning.Text = "加密默认关闭。本地工作区可包含明文密码，请限制数据目录访问。 / Encryption is off by default. The local workspace may contain plain-text passwords; restrict access to the data folder.";
        _encryptionWarning.Name = "encryptionWarning";

        _commandLineWarning.Dock = DockStyle.Top;
        _commandLineWarning.Height = 96;
        _commandLineWarning.TextMultiLine = true;
        _commandLineWarning.TextAlign = ContentAlignment.MiddleLeft;
        _commandLineWarning.Padding = new Padding(12, 8, 12, 8);
        _commandLineWarning.Text = "高风险：密码可通过命令行、连接 URI，或 RDP 临时文件中的 DPAPI password 51 自动传递；命令行和 URI 可能被进程列表、日志或审计工具记录。 / High risk: passwords may be passed automatically through command-line arguments, connection URIs, or DPAPI-protected password 51 in temporary RDP files; command-line and URI values may be recorded by process lists, logs, or auditing tools.";
        _commandLineWarning.Name = "commandLineWarning";

        _exportWarning.Dock = DockStyle.Top;
        _exportWarning.Height = 96;
        _exportWarning.TextMultiLine = true;
        _exportWarning.TextAlign = ContentAlignment.MiddleLeft;
        _exportWarning.Padding = new Padding(12, 8, 12, 8);
        _exportWarning.Text = "提醒：备注、客户端选项和自定义参数是自由文本，应用无法自动识别其中手写的 token/password；导出前请自行检查。 / Notes, client options, and custom arguments are free-form text. The app cannot automatically detect manually entered tokens/passwords in them; review exports before sharing.";
        _exportWarning.Name = "exportWarning";

        _puttyPathLabel.Dock = DockStyle.Fill;
        _puttyPathLabel.Margin = new Padding(8, 5, 4, 5);
        _puttyPathLabel.Name = "_puttyPathLabel";
        _puttyPathLabel.Text = "PuTTY";
        _puttyPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _puttyPathInput.PlaceholderText = "自动检测或选择 PuTTY / Auto-detect or browse";
        _puttyPathInput.AllowClear = true;
        _puttyPathInput.SuffixSvg = "FolderOpenOutlined";
        _puttyPathInput.Radius = 8;
        _puttyPathInput.Name = "puttyPathInput";

        _xshellPathLabel.Dock = DockStyle.Fill;
        _xshellPathLabel.Margin = new Padding(8, 5, 4, 5);
        _xshellPathLabel.Name = "_xshellPathLabel";
        _xshellPathLabel.Text = "Xshell";
        _xshellPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _xshellPathInput.PlaceholderText = "自动检测或选择 Xshell / Auto-detect or browse";
        _xshellPathInput.AllowClear = true;
        _xshellPathInput.SuffixSvg = "FolderOpenOutlined";
        _xshellPathInput.Radius = 8;
        _xshellPathInput.Name = "xshellPathInput";

        _xftpPathLabel.Dock = DockStyle.Fill;
        _xftpPathLabel.Margin = new Padding(8, 5, 4, 5);
        _xftpPathLabel.Name = "_xftpPathLabel";
        _xftpPathLabel.Text = "Xftp";
        _xftpPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _xftpPathInput.PlaceholderText = "自动检测或选择 Xftp / Auto-detect or browse";
        _xftpPathInput.AllowClear = true;
        _xftpPathInput.SuffixSvg = "FolderOpenOutlined";
        _xftpPathInput.Radius = 8;
        _xftpPathInput.Name = "xftpPathInput";

        _winscpPathLabel.Dock = DockStyle.Fill;
        _winscpPathLabel.Margin = new Padding(8, 5, 4, 5);
        _winscpPathLabel.Name = "_winscpPathLabel";
        _winscpPathLabel.Text = "WinSCP";
        _winscpPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _winscpPathInput.PlaceholderText = "自动检测或选择 WinSCP / Auto-detect or browse";
        _winscpPathInput.AllowClear = true;
        _winscpPathInput.SuffixSvg = "FolderOpenOutlined";
        _winscpPathInput.Radius = 8;
        _winscpPathInput.Name = "winscpPathInput";

        _secureCrtPathLabel.Dock = DockStyle.Fill;
        _secureCrtPathLabel.Margin = new Padding(8, 5, 4, 5);
        _secureCrtPathLabel.Name = "_secureCrtPathLabel";
        _secureCrtPathLabel.Text = "SecureCRT";
        _secureCrtPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _secureCrtPathInput.PlaceholderText = "自动检测或选择 SecureCRT / Auto-detect or browse";
        _secureCrtPathInput.AllowClear = true;
        _secureCrtPathInput.SuffixSvg = "FolderOpenOutlined";
        _secureCrtPathInput.Radius = 8;
        _secureCrtPathInput.Name = "secureCrtPathInput";

        _mobaXtermPathLabel.Dock = DockStyle.Fill;
        _mobaXtermPathLabel.Margin = new Padding(8, 5, 4, 5);
        _mobaXtermPathLabel.Name = "_mobaXtermPathLabel";
        _mobaXtermPathLabel.Text = "MobaXterm";
        _mobaXtermPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _mobaXtermPathInput.PlaceholderText = "自动检测或选择 MobaXterm / Auto-detect or browse";
        _mobaXtermPathInput.AllowClear = true;
        _mobaXtermPathInput.SuffixSvg = "FolderOpenOutlined";
        _mobaXtermPathInput.Radius = 8;
        _mobaXtermPathInput.Name = "mobaXtermPathInput";

        _tightVncPathLabel.Dock = DockStyle.Fill;
        _tightVncPathLabel.Margin = new Padding(8, 5, 4, 5);
        _tightVncPathLabel.Name = "_tightVncPathLabel";
        _tightVncPathLabel.Text = "TightVNC Viewer";
        _tightVncPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _tightVncPathInput.PlaceholderText = "自动检测或选择 TightVNC Viewer / Auto-detect or browse";
        _tightVncPathInput.AllowClear = true;
        _tightVncPathInput.SuffixSvg = "FolderOpenOutlined";
        _tightVncPathInput.Radius = 8;
        _tightVncPathInput.Name = "tightVncPathInput";

        _realVncPathLabel.Dock = DockStyle.Fill;
        _realVncPathLabel.Margin = new Padding(8, 5, 4, 5);
        _realVncPathLabel.Name = "_realVncPathLabel";
        _realVncPathLabel.Text = "RealVNC Viewer";
        _realVncPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _realVncPathInput.PlaceholderText = "自动检测或选择 RealVNC Viewer / Auto-detect or browse";
        _realVncPathInput.AllowClear = true;
        _realVncPathInput.SuffixSvg = "FolderOpenOutlined";
        _realVncPathInput.Radius = 8;
        _realVncPathInput.Name = "realVncPathInput";

        _ultraVncPathLabel.Dock = DockStyle.Fill;
        _ultraVncPathLabel.Margin = new Padding(8, 5, 4, 5);
        _ultraVncPathLabel.Name = "_ultraVncPathLabel";
        _ultraVncPathLabel.Text = "UltraVNC Viewer";
        _ultraVncPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _ultraVncPathInput.PlaceholderText = "自动检测或选择 UltraVNC Viewer / Auto-detect or browse";
        _ultraVncPathInput.AllowClear = true;
        _ultraVncPathInput.SuffixSvg = "FolderOpenOutlined";
        _ultraVncPathInput.Radius = 8;
        _ultraVncPathInput.Name = "ultraVncPathInput";

        _radminPathLabel.Dock = DockStyle.Fill;
        _radminPathLabel.Margin = new Padding(8, 5, 4, 5);
        _radminPathLabel.Name = "_radminPathLabel";
        _radminPathLabel.Text = "Radmin Viewer";
        _radminPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _radminPathInput.PlaceholderText = "自动检测或选择 Radmin Viewer / Auto-detect or browse";
        _radminPathInput.AllowClear = true;
        _radminPathInput.SuffixSvg = "FolderOpenOutlined";
        _radminPathInput.Radius = 8;
        _radminPathInput.Name = "radminPathInput";

        _toDeskPathLabel.Dock = DockStyle.Fill;
        _toDeskPathLabel.Margin = new Padding(8, 5, 4, 5);
        _toDeskPathLabel.Name = "_toDeskPathLabel";
        _toDeskPathLabel.Text = "ToDesk";
        _toDeskPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _toDeskPathInput.PlaceholderText = "自动检测或选择 ToDesk / Auto-detect or browse";
        _toDeskPathInput.AllowClear = true;
        _toDeskPathInput.SuffixSvg = "FolderOpenOutlined";
        _toDeskPathInput.Radius = 8;
        _toDeskPathInput.Name = "toDeskPathInput";

        _rustDeskPathLabel.Dock = DockStyle.Fill;
        _rustDeskPathLabel.Margin = new Padding(8, 5, 4, 5);
        _rustDeskPathLabel.Name = "_rustDeskPathLabel";
        _rustDeskPathLabel.Text = "RustDesk";
        _rustDeskPathLabel.TextAlign = ContentAlignment.MiddleLeft;

        _rustDeskPathInput.PlaceholderText = "自动检测或选择 RustDesk / Auto-detect or browse";
        _rustDeskPathInput.AllowClear = true;
        _rustDeskPathInput.SuffixSvg = "FolderOpenOutlined";
        _rustDeskPathInput.Radius = 8;
        _rustDeskPathInput.Name = "rustDeskPathInput";

        _openDataFolderLabel.Dock = DockStyle.Fill;
        _openDataFolderLabel.Margin = new Padding(8, 5, 4, 5);
        _openDataFolderLabel.Name = "_openDataFolderLabel";
        _openDataFolderLabel.Text = "应用数据 / App data";
        _openDataFolderLabel.TextAlign = ContentAlignment.MiddleLeft;

        _openDataFolderButton.Text = "打开数据文件夹 / Open data folder";
        _openDataFolderButton.IconSvg = "FolderOpenOutlined";
        _openDataFolderButton.Width = 220;
        _openDataFolderButton.Enabled = false;
        _openDataFolderButton.Name = "openDataFolderButton";

        _aboutLabel.Dock = DockStyle.Fill;
        _aboutLabel.Margin = new Padding(8, 5, 4, 5);
        _aboutLabel.Name = "_aboutLabel";
        _aboutLabel.Text = "产品信息 / Product";
        _aboutLabel.TextAlign = ContentAlignment.MiddleLeft;

        _aboutButton.Text = "关于与开源信息 / About and open source";
        _aboutButton.IconSvg = "InfoCircleOutlined";
        _aboutButton.Width = 240;
        _aboutButton.Name = "aboutButton";

        _saveButton.Text = "保存 / Save";
        _saveButton.Type = AntdUI.TTypeMini.Primary;
        _saveButton.Width = 112;
        _saveButton.Height = 38;
        _saveButton.Margin = new Padding(8, 0, 0, 0);
        _saveButton.Name = "saveButton";

        _cancelButton.Text = "取消 / Cancel";
        _cancelButton.Width = 104;
        _cancelButton.Height = 38;
        _cancelButton.Margin = new Padding(8, 0, 0, 0);
        _cancelButton.Name = "cancelButton";

        // Serialize editor bounds: AntdUI controls start at Size.Empty before runtime registration.
        _languageSelect.Margin = new Padding(4, 5, 10, 5);
        _languageSelect.TabIndex = 0;
        _languageSelect.Dock = DockStyle.Fill;
        _languageSelect.Size = new Size(240, 38);
        _themeSelect.Margin = new Padding(4, 5, 10, 5);
        _themeSelect.TabIndex = 1;
        _themeSelect.Dock = DockStyle.Fill;
        _themeSelect.Size = new Size(240, 38);
        _sidebarSwitch.Margin = new Padding(4, 5, 10, 5);
        _sidebarSwitch.TabIndex = 2;
        _sidebarSwitch.Anchor = AnchorStyles.Left;
        _sidebarSwitch.Size = new Size(60, 32);
        _encryptionSwitch.Margin = new Padding(4, 5, 10, 5);
        _encryptionSwitch.TabIndex = 3;
        _encryptionSwitch.Anchor = AnchorStyles.Left;
        _encryptionSwitch.Size = new Size(60, 32);
        _unsafePasswordSwitch.Margin = new Padding(4, 5, 10, 5);
        _unsafePasswordSwitch.TabIndex = 4;
        _unsafePasswordSwitch.Anchor = AnchorStyles.Left;
        _unsafePasswordSwitch.Size = new Size(60, 32);
        _includeSecretsSwitch.Margin = new Padding(4, 5, 10, 5);
        _includeSecretsSwitch.TabIndex = 5;
        _includeSecretsSwitch.Anchor = AnchorStyles.Left;
        _includeSecretsSwitch.Size = new Size(60, 32);
        _traySwitch.Margin = new Padding(4, 5, 10, 5);
        _traySwitch.TabIndex = 6;
        _traySwitch.Anchor = AnchorStyles.Left;
        _traySwitch.Size = new Size(60, 32);
        _confirmDeleteSwitch.Margin = new Padding(4, 5, 10, 5);
        _confirmDeleteSwitch.TabIndex = 7;
        _confirmDeleteSwitch.Anchor = AnchorStyles.Left;
        _confirmDeleteSwitch.Size = new Size(60, 32);
        _expiryDaysInput.Margin = new Padding(4, 5, 10, 5);
        _expiryDaysInput.TabIndex = 8;
        _expiryDaysInput.Dock = DockStyle.Fill;
        _expiryDaysInput.Size = new Size(240, 38);
        _pingTimeoutInput.Margin = new Padding(4, 5, 10, 5);
        _pingTimeoutInput.TabIndex = 9;
        _pingTimeoutInput.Dock = DockStyle.Fill;
        _pingTimeoutInput.Size = new Size(240, 38);
        _concurrencyInput.Margin = new Padding(4, 5, 10, 5);
        _concurrencyInput.TabIndex = 10;
        _concurrencyInput.Dock = DockStyle.Fill;
        _concurrencyInput.Size = new Size(240, 38);
        _puttyPathInput.Margin = new Padding(4, 5, 10, 5);
        _puttyPathInput.TabIndex = 11;
        _puttyPathInput.Dock = DockStyle.Fill;
        _puttyPathInput.Size = new Size(240, 38);
        _xshellPathInput.Margin = new Padding(4, 5, 10, 5);
        _xshellPathInput.TabIndex = 12;
        _xshellPathInput.Dock = DockStyle.Fill;
        _xshellPathInput.Size = new Size(240, 38);
        _xftpPathInput.Margin = new Padding(4, 5, 10, 5);
        _xftpPathInput.TabIndex = 13;
        _xftpPathInput.Dock = DockStyle.Fill;
        _xftpPathInput.Size = new Size(240, 38);
        _winscpPathInput.Margin = new Padding(4, 5, 10, 5);
        _winscpPathInput.TabIndex = 14;
        _winscpPathInput.Dock = DockStyle.Fill;
        _winscpPathInput.Size = new Size(240, 38);
        _secureCrtPathInput.Margin = new Padding(4, 5, 10, 5);
        _secureCrtPathInput.TabIndex = 15;
        _secureCrtPathInput.Dock = DockStyle.Fill;
        _secureCrtPathInput.Size = new Size(240, 38);
        _mobaXtermPathInput.Margin = new Padding(4, 5, 10, 5);
        _mobaXtermPathInput.TabIndex = 16;
        _mobaXtermPathInput.Dock = DockStyle.Fill;
        _mobaXtermPathInput.Size = new Size(240, 38);
        _tightVncPathInput.Margin = new Padding(4, 5, 10, 5);
        _tightVncPathInput.TabIndex = 17;
        _tightVncPathInput.Dock = DockStyle.Fill;
        _tightVncPathInput.Size = new Size(240, 38);
        _realVncPathInput.Margin = new Padding(4, 5, 10, 5);
        _realVncPathInput.TabIndex = 18;
        _realVncPathInput.Dock = DockStyle.Fill;
        _realVncPathInput.Size = new Size(240, 38);
        _ultraVncPathInput.Margin = new Padding(4, 5, 10, 5);
        _ultraVncPathInput.TabIndex = 19;
        _ultraVncPathInput.Dock = DockStyle.Fill;
        _ultraVncPathInput.Size = new Size(240, 38);
        _radminPathInput.Margin = new Padding(4, 5, 10, 5);
        _radminPathInput.TabIndex = 20;
        _radminPathInput.Dock = DockStyle.Fill;
        _radminPathInput.Size = new Size(240, 38);
        _toDeskPathInput.Margin = new Padding(4, 5, 10, 5);
        _toDeskPathInput.TabIndex = 21;
        _toDeskPathInput.Dock = DockStyle.Fill;
        _toDeskPathInput.Size = new Size(240, 38);
        _rustDeskPathInput.Margin = new Padding(4, 5, 10, 5);
        _rustDeskPathInput.TabIndex = 22;
        _rustDeskPathInput.Dock = DockStyle.Fill;
        _rustDeskPathInput.Size = new Size(240, 38);
        _openDataFolderButton.Margin = new Padding(4, 5, 10, 5);
        _openDataFolderButton.TabIndex = 23;
        _openDataFolderButton.Dock = DockStyle.Fill;
        _openDataFolderButton.Size = new Size(240, 38);
        _aboutButton.Margin = new Padding(4, 5, 10, 5);
        _aboutButton.TabIndex = 24;
        _aboutButton.Dock = DockStyle.Fill;
        _aboutButton.Size = new Size(240, 38);

        _appearanceGrid.AutoSize = true;
        _appearanceGrid.Dock = DockStyle.Top;
        _appearanceGrid.Size = new Size(864, 102);
        _appearanceGrid.ColumnCount = 4;
        _appearanceGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        _appearanceGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _appearanceGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        _appearanceGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _appearanceGrid.Controls.Add(_languageLabel, 0, 0);
        _appearanceGrid.Controls.Add(_languageSelect, 1, 0);
        _appearanceGrid.Controls.Add(_themeLabel, 2, 0);
        _appearanceGrid.Controls.Add(_themeSelect, 3, 0);
        _appearanceGrid.Controls.Add(_sidebarLabel, 0, 1);
        _appearanceGrid.Controls.Add(_sidebarSwitch, 1, 1);
        _appearanceGrid.Name = "appearanceGrid";
        _appearanceGrid.RowCount = 2;
        _appearanceGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _appearanceGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));

        _securityGrid.AutoSize = true;
        _securityGrid.Dock = DockStyle.Top;
        _securityGrid.Size = new Size(864, 102);
        _securityGrid.ColumnCount = 4;
        _securityGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        _securityGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _securityGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        _securityGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _securityGrid.Controls.Add(_encryptionLabel, 0, 0);
        _securityGrid.Controls.Add(_encryptionSwitch, 1, 0);
        _securityGrid.Controls.Add(_unsafePasswordLabel, 2, 0);
        _securityGrid.Controls.Add(_unsafePasswordSwitch, 3, 0);
        _securityGrid.Controls.Add(_includeSecretsLabel, 0, 1);
        _securityGrid.Controls.Add(_includeSecretsSwitch, 1, 1);
        _securityGrid.Name = "securityGrid";
        _securityGrid.RowCount = 2;
        _securityGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _securityGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));

        _behaviorGrid.AutoSize = true;
        _behaviorGrid.Dock = DockStyle.Top;
        _behaviorGrid.Size = new Size(864, 150);
        _behaviorGrid.ColumnCount = 4;
        _behaviorGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        _behaviorGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _behaviorGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        _behaviorGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _behaviorGrid.Controls.Add(_trayLabel, 0, 0);
        _behaviorGrid.Controls.Add(_traySwitch, 1, 0);
        _behaviorGrid.Controls.Add(_confirmDeleteLabel, 2, 0);
        _behaviorGrid.Controls.Add(_confirmDeleteSwitch, 3, 0);
        _behaviorGrid.Controls.Add(_expiryDaysLabel, 0, 1);
        _behaviorGrid.Controls.Add(_expiryDaysInput, 1, 1);
        _behaviorGrid.Controls.Add(_pingTimeoutLabel, 2, 1);
        _behaviorGrid.Controls.Add(_pingTimeoutInput, 3, 1);
        _behaviorGrid.Controls.Add(_concurrencyLabel, 0, 2);
        _behaviorGrid.Controls.Add(_concurrencyInput, 1, 2);
        _behaviorGrid.Name = "behaviorGrid";
        _behaviorGrid.RowCount = 3;
        _behaviorGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _behaviorGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _behaviorGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));

        _toolPathGrid.AutoSize = true;
        _toolPathGrid.Dock = DockStyle.Top;
        _toolPathGrid.Size = new Size(864, 342);
        _toolPathGrid.ColumnCount = 4;
        _toolPathGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        _toolPathGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _toolPathGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        _toolPathGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        _toolPathGrid.Controls.Add(_puttyPathLabel, 0, 0);
        _toolPathGrid.Controls.Add(_puttyPathInput, 1, 0);
        _toolPathGrid.Controls.Add(_xshellPathLabel, 2, 0);
        _toolPathGrid.Controls.Add(_xshellPathInput, 3, 0);
        _toolPathGrid.Controls.Add(_xftpPathLabel, 0, 1);
        _toolPathGrid.Controls.Add(_xftpPathInput, 1, 1);
        _toolPathGrid.Controls.Add(_winscpPathLabel, 2, 1);
        _toolPathGrid.Controls.Add(_winscpPathInput, 3, 1);
        _toolPathGrid.Controls.Add(_secureCrtPathLabel, 0, 2);
        _toolPathGrid.Controls.Add(_secureCrtPathInput, 1, 2);
        _toolPathGrid.Controls.Add(_mobaXtermPathLabel, 2, 2);
        _toolPathGrid.Controls.Add(_mobaXtermPathInput, 3, 2);
        _toolPathGrid.Controls.Add(_tightVncPathLabel, 0, 3);
        _toolPathGrid.Controls.Add(_tightVncPathInput, 1, 3);
        _toolPathGrid.Controls.Add(_realVncPathLabel, 2, 3);
        _toolPathGrid.Controls.Add(_realVncPathInput, 3, 3);
        _toolPathGrid.Controls.Add(_ultraVncPathLabel, 0, 4);
        _toolPathGrid.Controls.Add(_ultraVncPathInput, 1, 4);
        _toolPathGrid.Controls.Add(_radminPathLabel, 2, 4);
        _toolPathGrid.Controls.Add(_radminPathInput, 3, 4);
        _toolPathGrid.Controls.Add(_toDeskPathLabel, 0, 5);
        _toolPathGrid.Controls.Add(_toDeskPathInput, 1, 5);
        _toolPathGrid.Controls.Add(_rustDeskPathLabel, 2, 5);
        _toolPathGrid.Controls.Add(_rustDeskPathInput, 3, 5);
        _toolPathGrid.Controls.Add(_openDataFolderLabel, 0, 6);
        _toolPathGrid.Controls.Add(_openDataFolderButton, 1, 6);
        _toolPathGrid.Controls.Add(_aboutLabel, 2, 6);
        _toolPathGrid.Controls.Add(_aboutButton, 3, 6);
        _toolPathGrid.Name = "toolPathGrid";
        _toolPathGrid.RowCount = 7;
        _toolPathGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _toolPathGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _toolPathGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _toolPathGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _toolPathGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _toolPathGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        _toolPathGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));

        _appearanceTitle.Dock = DockStyle.Top;
        _appearanceTitle.Height = 36;
        _appearanceTitle.Text = "外观 / Appearance";
        _appearanceTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        _appearanceTitle.TextAlign = ContentAlignment.MiddleLeft;
        _appearanceTitle.Padding = new Padding(12, 0, 8, 0);
        _appearanceTitle.Name = "appearanceTitle";

        _securityTitle.Dock = DockStyle.Top;
        _securityTitle.Height = 36;
        _securityTitle.Text = "安全 / Security";
        _securityTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        _securityTitle.TextAlign = ContentAlignment.MiddleLeft;
        _securityTitle.Padding = new Padding(12, 0, 8, 0);
        _securityTitle.Name = "securityTitle";

        _encryptionNoticeTitle.Dock = DockStyle.Top;
        _encryptionNoticeTitle.Height = 36;
        _encryptionNoticeTitle.Text = "加密状态 / Encryption notice";
        _encryptionNoticeTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        _encryptionNoticeTitle.TextAlign = ContentAlignment.MiddleLeft;
        _encryptionNoticeTitle.Padding = new Padding(12, 0, 8, 0);
        _encryptionNoticeTitle.Name = "encryptionNoticeTitle";

        _commandLineNoticeTitle.Dock = DockStyle.Top;
        _commandLineNoticeTitle.Height = 36;
        _commandLineNoticeTitle.Text = "自动传密风险 / Automatic password notice";
        _commandLineNoticeTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        _commandLineNoticeTitle.TextAlign = ContentAlignment.MiddleLeft;
        _commandLineNoticeTitle.Padding = new Padding(12, 0, 8, 0);
        _commandLineNoticeTitle.Name = "commandLineNoticeTitle";

        _exportNoticeTitle.Dock = DockStyle.Top;
        _exportNoticeTitle.Height = 36;
        _exportNoticeTitle.Text = "导出内容提醒 / Export content notice";
        _exportNoticeTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        _exportNoticeTitle.TextAlign = ContentAlignment.MiddleLeft;
        _exportNoticeTitle.Padding = new Padding(12, 0, 8, 0);
        _exportNoticeTitle.Name = "exportNoticeTitle";

        _behaviorTitle.Dock = DockStyle.Top;
        _behaviorTitle.Height = 36;
        _behaviorTitle.Text = "行为与监测 / Behavior and monitoring";
        _behaviorTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        _behaviorTitle.TextAlign = ContentAlignment.MiddleLeft;
        _behaviorTitle.Padding = new Padding(12, 0, 8, 0);
        _behaviorTitle.Name = "behaviorTitle";

        _clientsTitle.Dock = DockStyle.Top;
        _clientsTitle.Height = 36;
        _clientsTitle.Text = "外部客户端 / External clients";
        _clientsTitle.Font = new Font("Segoe UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        _clientsTitle.TextAlign = ContentAlignment.MiddleLeft;
        _clientsTitle.Padding = new Padding(12, 0, 8, 0);
        _clientsTitle.Name = "clientsTitle";

        _appearanceSection.Radius = 10;
        _appearanceSection.BorderWidth = 1F;
        _appearanceSection.Margin = new Padding(0, 0, 0, 12);
        _appearanceSection.Padding = new Padding(8);
        _appearanceSection.Width = 880;
        _appearanceSection.Height = 196;
        _appearanceSection.Name = "appearanceSection";
        _appearanceSection.Controls.Add(_appearanceGrid);
        _appearanceSection.Controls.Add(_appearanceTitle);

        _securitySection.Radius = 10;
        _securitySection.BorderWidth = 1F;
        _securitySection.Margin = new Padding(0, 0, 0, 12);
        _securitySection.Padding = new Padding(8);
        _securitySection.Width = 880;
        _securitySection.Height = 196;
        _securitySection.Name = "securitySection";
        _securitySection.Controls.Add(_securityGrid);
        _securitySection.Controls.Add(_securityTitle);

        _encryptionNoticeSection.Radius = 10;
        _encryptionNoticeSection.BorderWidth = 1F;
        _encryptionNoticeSection.Margin = new Padding(0, 0, 0, 12);
        _encryptionNoticeSection.Padding = new Padding(8);
        _encryptionNoticeSection.Width = 880;
        _encryptionNoticeSection.Height = 148;
        _encryptionNoticeSection.Name = "encryptionNoticeSection";
        _encryptionNoticeSection.Controls.Add(_encryptionWarning);
        _encryptionNoticeSection.Controls.Add(_encryptionNoticeTitle);

        _commandLineNoticeSection.Radius = 10;
        _commandLineNoticeSection.BorderWidth = 1F;
        _commandLineNoticeSection.Margin = new Padding(0, 0, 0, 12);
        _commandLineNoticeSection.Padding = new Padding(8);
        _commandLineNoticeSection.Width = 880;
        _commandLineNoticeSection.Height = 148;
        _commandLineNoticeSection.Name = "commandLineNoticeSection";
        _commandLineNoticeSection.Controls.Add(_commandLineWarning);
        _commandLineNoticeSection.Controls.Add(_commandLineNoticeTitle);

        _exportNoticeSection.Radius = 10;
        _exportNoticeSection.BorderWidth = 1F;
        _exportNoticeSection.Margin = new Padding(0, 0, 0, 12);
        _exportNoticeSection.Padding = new Padding(8);
        _exportNoticeSection.Width = 880;
        _exportNoticeSection.Height = 148;
        _exportNoticeSection.Name = "exportNoticeSection";
        _exportNoticeSection.Controls.Add(_exportWarning);
        _exportNoticeSection.Controls.Add(_exportNoticeTitle);

        _behaviorSection.Radius = 10;
        _behaviorSection.BorderWidth = 1F;
        _behaviorSection.Margin = new Padding(0, 0, 0, 12);
        _behaviorSection.Padding = new Padding(8);
        _behaviorSection.Width = 880;
        _behaviorSection.Height = 292;
        _behaviorSection.Name = "behaviorSection";
        _behaviorSection.Controls.Add(_behaviorGrid);
        _behaviorSection.Controls.Add(_behaviorTitle);

        _clientsSection.Radius = 10;
        _clientsSection.BorderWidth = 1F;
        _clientsSection.Margin = new Padding(0, 0, 0, 12);
        _clientsSection.Padding = new Padding(8);
        _clientsSection.Width = 880;
        _clientsSection.Height = 388;
        _clientsSection.Name = "clientsSection";
        _clientsSection.Controls.Add(_toolPathGrid);
        _clientsSection.Controls.Add(_clientsTitle);

        _contentFlow.Controls.Add(_appearanceSection);
        _contentFlow.Controls.Add(_securitySection);
        _contentFlow.Controls.Add(_encryptionNoticeSection);
        _contentFlow.Controls.Add(_commandLineNoticeSection);
        _contentFlow.Controls.Add(_exportNoticeSection);
        _contentFlow.Controls.Add(_behaviorSection);
        _contentFlow.Controls.Add(_clientsSection);
        _footerFlow.Controls.Add(_saveButton);
        _footerFlow.Controls.Add(_cancelButton);
        AcceptButton = _saveButton;
        CancelButton = _cancelButton;
        _header.Text = "设置 / Settings";
        MinimumSize = new Size(680, 500);
        ClientSize = new Size(940, 720);
        Name = "SettingsForm";
        Text = "设置 / Settings";
        _appearanceGrid.ResumeLayout(false);
        _appearanceGrid.PerformLayout();
        _securityGrid.ResumeLayout(false);
        _securityGrid.PerformLayout();
        _behaviorGrid.ResumeLayout(false);
        _behaviorGrid.PerformLayout();
        _toolPathGrid.ResumeLayout(false);
        _toolPathGrid.PerformLayout();
        _appearanceSection.ResumeLayout(false);
        _appearanceSection.PerformLayout();
        _securitySection.ResumeLayout(false);
        _securitySection.PerformLayout();
        _encryptionNoticeSection.ResumeLayout(false);
        _encryptionNoticeSection.PerformLayout();
        _commandLineNoticeSection.ResumeLayout(false);
        _commandLineNoticeSection.PerformLayout();
        _exportNoticeSection.ResumeLayout(false);
        _exportNoticeSection.PerformLayout();
        _behaviorSection.ResumeLayout(false);
        _behaviorSection.PerformLayout();
        _clientsSection.ResumeLayout(false);
        _clientsSection.PerformLayout();
        _contentFlow.ResumeLayout(false);
        _contentFlow.PerformLayout();
        _footerFlow.ResumeLayout(false);
        ResumeLayout(false);
    }

    private AntdUI.Label _languageLabel = null!;
    private AntdUI.Select _languageSelect = null!;
    private AntdUI.Label _themeLabel = null!;
    private AntdUI.Select _themeSelect = null!;
    private AntdUI.Label _encryptionLabel = null!;
    private AntdUI.Switch _encryptionSwitch = null!;
    private AntdUI.Label _unsafePasswordLabel = null!;
    private AntdUI.Switch _unsafePasswordSwitch = null!;
    private AntdUI.Label _includeSecretsLabel = null!;
    private AntdUI.Switch _includeSecretsSwitch = null!;
    private AntdUI.Label _trayLabel = null!;
    private AntdUI.Switch _traySwitch = null!;
    private AntdUI.Label _confirmDeleteLabel = null!;
    private AntdUI.Switch _confirmDeleteSwitch = null!;
    private AntdUI.Label _sidebarLabel = null!;
    private AntdUI.Switch _sidebarSwitch = null!;
    private AntdUI.Label _expiryDaysLabel = null!;
    private AntdUI.InputNumber _expiryDaysInput = null!;
    private AntdUI.Label _pingTimeoutLabel = null!;
    private AntdUI.InputNumber _pingTimeoutInput = null!;
    private AntdUI.Label _concurrencyLabel = null!;
    private AntdUI.InputNumber _concurrencyInput = null!;
    private AntdUI.Label _encryptionWarning = null!;
    private AntdUI.Label _commandLineWarning = null!;
    private AntdUI.Label _exportWarning = null!;
    private AntdUI.Label _puttyPathLabel = null!;
    private AntdUI.Input _puttyPathInput = null!;
    private AntdUI.Label _xshellPathLabel = null!;
    private AntdUI.Input _xshellPathInput = null!;
    private AntdUI.Label _xftpPathLabel = null!;
    private AntdUI.Input _xftpPathInput = null!;
    private AntdUI.Label _winscpPathLabel = null!;
    private AntdUI.Input _winscpPathInput = null!;
    private AntdUI.Label _secureCrtPathLabel = null!;
    private AntdUI.Input _secureCrtPathInput = null!;
    private AntdUI.Label _mobaXtermPathLabel = null!;
    private AntdUI.Input _mobaXtermPathInput = null!;
    private AntdUI.Label _tightVncPathLabel = null!;
    private AntdUI.Input _tightVncPathInput = null!;
    private AntdUI.Label _realVncPathLabel = null!;
    private AntdUI.Input _realVncPathInput = null!;
    private AntdUI.Label _ultraVncPathLabel = null!;
    private AntdUI.Input _ultraVncPathInput = null!;
    private AntdUI.Label _radminPathLabel = null!;
    private AntdUI.Input _radminPathInput = null!;
    private AntdUI.Label _toDeskPathLabel = null!;
    private AntdUI.Input _toDeskPathInput = null!;
    private AntdUI.Label _rustDeskPathLabel = null!;
    private AntdUI.Input _rustDeskPathInput = null!;
    private AntdUI.Label _openDataFolderLabel = null!;
    private AntdUI.Button _openDataFolderButton = null!;
    private AntdUI.Label _aboutLabel = null!;
    private AntdUI.Button _aboutButton = null!;
    private AntdUI.Button _saveButton = null!;
    private AntdUI.Button _cancelButton = null!;
    private ResponsiveFieldGrid _appearanceGrid = null!;
    private ResponsiveFieldGrid _securityGrid = null!;
    private ResponsiveFieldGrid _behaviorGrid = null!;
    private ResponsiveFieldGrid _toolPathGrid = null!;
    private AntdUI.Panel _appearanceSection = null!;
    private AntdUI.Panel _securitySection = null!;
    private AntdUI.Panel _encryptionNoticeSection = null!;
    private AntdUI.Panel _commandLineNoticeSection = null!;
    private AntdUI.Panel _exportNoticeSection = null!;
    private AntdUI.Panel _behaviorSection = null!;
    private AntdUI.Panel _clientsSection = null!;
    private AntdUI.Label _appearanceTitle = null!;
    private AntdUI.Label _securityTitle = null!;
    private AntdUI.Label _encryptionNoticeTitle = null!;
    private AntdUI.Label _commandLineNoticeTitle = null!;
    private AntdUI.Label _exportNoticeTitle = null!;
    private AntdUI.Label _behaviorTitle = null!;
    private AntdUI.Label _clientsTitle = null!;
}
